import unittest

from App.data.release import Release
from App.repositories.metadata_repository import MetadataRepository
from Test.Lib.mock_metadata_client import MockMetadataClient


class MetadataRepositoryTest(unittest.TestCase):

    def test_add_metadata(self):

        releases = [
            Release(author='Jamie xx', title='In Waves', type='album'),
            Release(author='Katy Perry', title='143', type='album'),
            Release(author='Future', title='MIXTAPE PLUTO', type='album'),
            Release(author='The Voidz', title='Like All Before You', type='album'),
            Release(author='The Alchemist', title='The Genuine Articulate', type='album')
        ]

        mocked_album_metadata = [
            {'album_type': 'album', 'total_tracks': 12,
             'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
                                   'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE',
                                   'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE',
                                   'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD',
                                   'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM',
                                   'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL',
                                   'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ',
                                   'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM',
                                   'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM',
                                   'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN',
                                   'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
                                   'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
                                   'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
                                   'VE', 'ET', 'XK'],
             'external_urls': {'spotify': 'https://open.spotify.com/album/57MSBg5pBQZH5bfLVDmeuP'},
             'href': 'https://api.spotify.com/v1/albums/57MSBg5pBQZH5bfLVDmeuP', 'id': '57MSBg5pBQZH5bfLVDmeuP',
             'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2733126a95bb7ed4146a80c7fc6',
                         'width': 640},
                        {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e023126a95bb7ed4146a80c7fc6',
                         'width': 300},
                        {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048513126a95bb7ed4146a80c7fc6',
                         'width': 64}], 'name': 'In Waves', 'release_date': '2024-09-20',
             'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:57MSBg5pBQZH5bfLVDmeuP',
             'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ'},
                          'href': 'https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ',
                          'id': '7A0awCXkE1FtSU8B0qwOJQ', 'name': 'Jamie xx', 'type': 'artist',
                          'uri': 'spotify:artist:7A0awCXkE1FtSU8B0qwOJQ'}]},
            {'album_type': 'album', 'total_tracks': 15,
             'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
                                   'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE',
                                   'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE',
                                   'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD',
                                   'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM',
                                   'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'KZ', 'MD', 'UA', 'AL', 'BA',
                                   'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG',
                                   'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE',
                                   'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA',
                                   'NR', 'NE', 'PW', 'PG', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC',
                                   'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ',
                                   'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ',
                                   'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET',
                                   'XK'],
             'external_urls': {'spotify': 'https://open.spotify.com/album/5Xd0KCzb0EJtPbUEiyxYVH'},
             'href': 'https://api.spotify.com/v1/albums/5Xd0KCzb0EJtPbUEiyxYVH', 'id': '5Xd0KCzb0EJtPbUEiyxYVH',
             'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273ddac71a12622bdc7e9d3e795',
                         'width': 640},
                        {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02ddac71a12622bdc7e9d3e795',
                         'width': 300},
                        {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851ddac71a12622bdc7e9d3e795',
                         'width': 64}], 'name': '143', 'release_date': '2024-12-20', 'release_date_precision': 'day',
             'type': 'album', 'uri': 'spotify:album:5Xd0KCzb0EJtPbUEiyxYVH', 'artists': [
                {'external_urls': {'spotify': 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X'},
                 'href': 'https://api.spotify.com/v1/artists/6jJ0s89eD6GaHleKKya26X', 'id': '6jJ0s89eD6GaHleKKya26X',
                 'name': 'Katy Perry', 'type': 'artist', 'uri': 'spotify:artist:6jJ0s89eD6GaHleKKya26X'}]},
            {'album_type': 'album', 'total_tracks': 17,
             'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
                                   'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE',
                                   'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE',
                                   'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD',
                                   'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM',
                                   'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL',
                                   'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ',
                                   'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM',
                                   'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM',
                                   'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN',
                                   'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
                                   'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
                                   'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
                                   'VE', 'ET', 'XK'],
             'external_urls': {'spotify': 'https://open.spotify.com/album/4Zoxsc06EUHRf5GrJPJZ54'},
             'href': 'https://api.spotify.com/v1/albums/4Zoxsc06EUHRf5GrJPJZ54', 'id': '4Zoxsc06EUHRf5GrJPJZ54',
             'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b27376c5a1960013e9203bcd6cd5',
                         'width': 640},
                        {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e0276c5a1960013e9203bcd6cd5',
                         'width': 300},
                        {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d0000485176c5a1960013e9203bcd6cd5',
                         'width': 64}], 'name': 'MIXTAPE PLUTO', 'release_date': '2024-09-20',
             'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:4Zoxsc06EUHRf5GrJPJZ54',
             'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1RyvyyTE3xzB2ZywiAwp0i'},
                          'href': 'https://api.spotify.com/v1/artists/1RyvyyTE3xzB2ZywiAwp0i',
                          'id': '1RyvyyTE3xzB2ZywiAwp0i', 'name': 'Future', 'type': 'artist',
                          'uri': 'spotify:artist:1RyvyyTE3xzB2ZywiAwp0i'}]},
            {'album_type': 'album', 'total_tracks': 10,
             'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
                                   'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE',
                                   'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE',
                                   'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD',
                                   'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM',
                                   'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL',
                                   'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ',
                                   'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM',
                                   'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM',
                                   'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN',
                                   'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
                                   'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
                                   'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
                                   'VE', 'ET', 'XK'],
             'external_urls': {'spotify': 'https://open.spotify.com/album/7h0Y4HcaDsuLnXeYmvY7ai'},
             'href': 'https://api.spotify.com/v1/albums/7h0Y4HcaDsuLnXeYmvY7ai', 'id': '7h0Y4HcaDsuLnXeYmvY7ai',
             'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273ee5737c5a60216441f49e376',
                         'width': 640},
                        {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02ee5737c5a60216441f49e376',
                         'width': 300},
                        {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851ee5737c5a60216441f49e376',
                         'width': 64}], 'name': 'Like All Before You', 'release_date': '2024-09-20',
             'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:7h0Y4HcaDsuLnXeYmvY7ai',
             'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4nUBBtLtzqZGpdiynTJbYJ'},
                          'href': 'https://api.spotify.com/v1/artists/4nUBBtLtzqZGpdiynTJbYJ',
                          'id': '4nUBBtLtzqZGpdiynTJbYJ', 'name': 'The Voidz', 'type': 'artist',
                          'uri': 'spotify:artist:4nUBBtLtzqZGpdiynTJbYJ'}]},
            {'album_type': 'album', 'total_tracks': 8,
             'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
                                   'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE',
                                   'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE',
                                   'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD',
                                   'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM',
                                   'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL',
                                   'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ',
                                   'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM',
                                   'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM',
                                   'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN',
                                   'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
                                   'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
                                   'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
                                   'VE', 'ET', 'XK'],
             'external_urls': {'spotify': 'https://open.spotify.com/album/3EzeDYzLp9bcuK162KVDMp'},
             'href': 'https://api.spotify.com/v1/albums/3EzeDYzLp9bcuK162KVDMp', 'id': '3EzeDYzLp9bcuK162KVDMp',
             'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d47b3c75a1a3f223036be64c',
                         'width': 640},
                        {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d47b3c75a1a3f223036be64c',
                         'width': 300},
                        {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d47b3c75a1a3f223036be64c',
                         'width': 64}], 'name': 'The Genuine Articulate', 'release_date': '2024-09-20',
             'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:3EzeDYzLp9bcuK162KVDMp',
             'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0eVyjRhzZKke2KFYTcDkeu'},
                          'href': 'https://api.spotify.com/v1/artists/0eVyjRhzZKke2KFYTcDkeu',
                          'id': '0eVyjRhzZKke2KFYTcDkeu', 'name': 'The Alchemist', 'type': 'artist',
                          'uri': 'spotify:artist:0eVyjRhzZKke2KFYTcDkeu'}]}

        ]
        mocked_artist_metadata = [
            {'external_urls': {'spotify': 'https://open.spotify.com/artist/4rj3KWaLAnuxgtMMkypZhf'},
             'followers': {'href': None, 'total': 14807}, 'genres': ['italian pop'],
             'href': 'https://api.spotify.com/v1/artists/4rj3KWaLAnuxgtMMkypZhf', 'id': '4rj3KWaLAnuxgtMMkypZhf',
             'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb6a03515ae09c37bd80cc99a8', 'height': 640,
                         'width': 640},
                        {'url': 'https://i.scdn.co/image/ab676161000051746a03515ae09c37bd80cc99a8', 'height': 320,
                         'width': 320},
                        {'url': 'https://i.scdn.co/image/ab6761610000f1786a03515ae09c37bd80cc99a8', 'height': 160,
                         'width': 160}], 'name': 'Jamie xx', 'popularity': 74, 'type': 'artist',
             'uri': 'spotify:artist:4rj3KWaLAnuxgtMMkypZhf'},
            {'external_urls': {'spotify': 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X'},
             'followers': {'href': None, 'total': 35670205}, 'genres': ['pop'],
             'href': 'https://api.spotify.com/v1/artists/6jJ0s89eD6GaHleKKya26X', 'id': '6jJ0s89eD6GaHleKKya26X',
             'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb0988562f78810e47a6e3325f', 'height': 640,
                         'width': 640},
                        {'url': 'https://i.scdn.co/image/ab676161000051740988562f78810e47a6e3325f', 'height': 320,
                         'width': 320},
                        {'url': 'https://i.scdn.co/image/ab6761610000f1780988562f78810e47a6e3325f', 'height': 160,
                         'width': 160}], 'name': 'Katy Perry', 'popularity': 87, 'type': 'artist',
             'uri': 'spotify:artist:6jJ0s89eD6GaHleKKya26X'},
            {'external_urls': {'spotify': 'https://open.spotify.com/artist/1RyvyyTE3xzB2ZywiAwp0i'},
             'followers': {'href': None, 'total': 20000243},
             'genres': ['atl hip hop', 'hip hop', 'rap', 'southern hip hop', 'trap'],
             'href': 'https://api.spotify.com/v1/artists/1RyvyyTE3xzB2ZywiAwp0i', 'id': '1RyvyyTE3xzB2ZywiAwp0i',
             'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb7565b356bc9d9394eefa2ccb', 'height': 640,
                         'width': 640},
                        {'url': 'https://i.scdn.co/image/ab676161000051747565b356bc9d9394eefa2ccb', 'height': 320,
                         'width': 320},
                        {'url': 'https://i.scdn.co/image/ab6761610000f1787565b356bc9d9394eefa2ccb', 'height': 160,
                         'width': 160}], 'name': 'Future', 'popularity': 93, 'type': 'artist',
             'uri': 'spotify:artist:1RyvyyTE3xzB2ZywiAwp0i'},
            {'external_urls': {'spotify': 'https://open.spotify.com/artist/2rasxNiJk2a3rNeGFss3x5'},
             'followers': {'href': None, 'total': 14046}, 'genres': ['modern alternative rock'],
             'href': 'https://api.spotify.com/v1/artists/2rasxNiJk2a3rNeGFss3x5', 'id': '2rasxNiJk2a3rNeGFss3x5',
             'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebe4f5ea24a1064015a57b9a0e', 'height': 640,
                         'width': 640},
                        {'url': 'https://i.scdn.co/image/ab67616100005174e4f5ea24a1064015a57b9a0e', 'height': 320,
                         'width': 320},
                        {'url': 'https://i.scdn.co/image/ab6761610000f178e4f5ea24a1064015a57b9a0e', 'height': 160,
                         'width': 160}], 'name': 'The Voidz', 'popularity': 44, 'type': 'artist',
             'uri': 'spotify:artist:2rasxNiJk2a3rNeGFss3x5'},
            {'external_urls': {'spotify': 'https://open.spotify.com/artist/4wEzanUDeA8SB82tGH8gc1'},
             'followers': {'href': None, 'total': 3}, 'genres': ['alternative hip hop', 'drumless hip hop', 'hip hop',
                            'instrumental hip hop', 'west coast rap'],
             'href': 'https://api.spotify.com/v1/artists/4wEzanUDeA8SB82tGH8gc1', 'id': '4wEzanUDeA8SB82tGH8gc1',
             'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b27340bed0d26dd5fac71e9df080', 'height': 640,
                         'width': 640},
                        {'url': 'https://i.scdn.co/image/ab67616d00001e0240bed0d26dd5fac71e9df080', 'height': 300,
                         'width': 300},
                        {'url': 'https://i.scdn.co/image/ab67616d0000485140bed0d26dd5fac71e9df080', 'height': 64,
                         'width': 64}], 'name': 'The Alchemist', 'popularity': 0, 'type': 'artist',
             'uri': 'spotify:artist:4wEzanUDeA8SB82tGH8gc1'}
        ]

        expected_metadata_releases = [
            Release(author='Jamie xx', title='In Waves', type='album',
                    url='https://open.spotify.com/album/57MSBg5pBQZH5bfLVDmeuP',
                    genres=['italian pop']),
            Release(author='Katy Perry', title='143', type='album',
                    url='https://open.spotify.com/album/5Xd0KCzb0EJtPbUEiyxYVH',
                    genres=['pop']),
            Release(author='Future', title='MIXTAPE PLUTO', type='album',
                    url='https://open.spotify.com/album/4Zoxsc06EUHRf5GrJPJZ54',
                    genres=['atl hip hop', 'hip hop', 'rap', 'southern hip hop', 'trap']),
            Release(author='The Voidz', title='Like All Before You', type='album',
                    url='https://open.spotify.com/album/7h0Y4HcaDsuLnXeYmvY7ai',
                    genres=['modern alternative rock']),
            Release(author='The Alchemist', title='The Genuine Articulate', type='album',
                    url='https://open.spotify.com/album/3EzeDYzLp9bcuK162KVDMp',
                    genres=['alternative hip hop', 'drumless hip hop', 'hip hop',
                            'instrumental hip hop', 'west coast rap']),
        ]

        metadata_repository = MetadataRepository(MockMetadataClient(mocked_album_metadata, mocked_artist_metadata))
        complete_releases = metadata_repository.add_metadata(releases=releases)

        self.assertEqual(
            [release.__dict__ for release in expected_metadata_releases],
            [release.__dict__ for release in complete_releases]
        )

