import unittest

from App.data.release import Release
from App.services.spotify_metadata_client import SpotifyMetadataClient
from Test.Lib.mock_spotify import MockSpotify


class MetadataRepositoryTest(unittest.TestCase):

    def test_search_album(self):
        title = 'In Waves'
        artist = 'Jamie xx'

        mocked_album_response = {'In%20Waves%20artist:Jamie%20xx': {'albums': {'href': 'https://api.spotify.com/v1/search?offset=0&limit=1&query=In%2520Waves%2520artist%3AJamiexx&type=album', 'limit': 1, 'next': 'https://api.spotify.com/v1/search?offset=1&limit=1&query=In%2520Waves%2520artist%3AJamiexx&type=album', 'offset': 0, 'previous': None, 'total': 797, 'items': [{'album_type': 'album', 'total_tracks': 12, 'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'], 'external_urls': {'spotify': 'https://open.spotify.com/album/57MSBg5pBQZH5bfLVDmeuP'}, 'href': 'https://api.spotify.com/v1/albums/57MSBg5pBQZH5bfLVDmeuP', 'id': '57MSBg5pBQZH5bfLVDmeuP', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2733126a95bb7ed4146a80c7fc6', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e023126a95bb7ed4146a80c7fc6', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048513126a95bb7ed4146a80c7fc6', 'width': 64}], 'name': 'In Waves', 'release_date': '2024-09-20', 'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:57MSBg5pBQZH5bfLVDmeuP', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ'}, 'href': 'https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ', 'id': '7A0awCXkE1FtSU8B0qwOJQ', 'name': 'Jamie xx', 'type': 'artist', 'uri': 'spotify:artist:7A0awCXkE1FtSU8B0qwOJQ'}]}]}}}

        expected_albums_metadata = {'album_type': 'album', 'total_tracks': 12, 'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'], 'external_urls': {'spotify': 'https://open.spotify.com/album/57MSBg5pBQZH5bfLVDmeuP'}, 'href': 'https://api.spotify.com/v1/albums/57MSBg5pBQZH5bfLVDmeuP', 'id': '57MSBg5pBQZH5bfLVDmeuP', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2733126a95bb7ed4146a80c7fc6', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e023126a95bb7ed4146a80c7fc6', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048513126a95bb7ed4146a80c7fc6', 'width': 64}], 'name': 'In Waves', 'release_date': '2024-09-20', 'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:57MSBg5pBQZH5bfLVDmeuP', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ'}, 'href': 'https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ', 'id': '7A0awCXkE1FtSU8B0qwOJQ', 'name': 'Jamie xx', 'type': 'artist', 'uri': 'spotify:artist:7A0awCXkE1FtSU8B0qwOJQ'}]}

        metadata_client = SpotifyMetadataClient(MockSpotify(mocked_album_response))
        album_metadata = metadata_client.search_album(title=title, artist=artist)

        self.assertEqual(expected_albums_metadata , album_metadata)

    def test_search_artist(self):
        artist = 'Jamie xx'

        mocked_artist_response = {'Jamie%20xx': {'artists': {'href': 'https://api.spotify.com/v1/search?offset=0&limit=1&query=Jamiexx&type=artist', 'limit': 1, 'next': 'https://api.spotify.com/v1/search?offset=1&limit=1&query=Jamiexx&type=artist', 'offset': 0, 'previous': None, 'total': 802, 'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ'}, 'followers': {'href': None, 'total': 890190}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ', 'id': '7A0awCXkE1FtSU8B0qwOJQ', 'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb5b2ba819fa89b17d6ae81567', 'height': 640, 'width': 640}, {'url': 'https://i.scdn.co/image/ab676161000051745b2ba819fa89b17d6ae81567', 'height': 320, 'width': 320}, {'url': 'https://i.scdn.co/image/ab6761610000f1785b2ba819fa89b17d6ae81567', 'height': 160, 'width': 160}], 'name': 'Jamie xx', 'popularity': 65, 'type': 'artist', 'uri': 'spotify:artist:7A0awCXkE1FtSU8B0qwOJQ'}]}}}

        expected_artist_metadata = {'external_urls': {'spotify': 'https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ'}, 'followers': {'href': None, 'total': 890190}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ', 'id': '7A0awCXkE1FtSU8B0qwOJQ', 'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5eb5b2ba819fa89b17d6ae81567', 'height': 640, 'width': 640}, {'url': 'https://i.scdn.co/image/ab676161000051745b2ba819fa89b17d6ae81567', 'height': 320, 'width': 320}, {'url': 'https://i.scdn.co/image/ab6761610000f1785b2ba819fa89b17d6ae81567', 'height': 160, 'width': 160}], 'name': 'Jamie xx', 'popularity': 65, 'type': 'artist', 'uri': 'spotify:artist:7A0awCXkE1FtSU8B0qwOJQ'}

        metadata_client = SpotifyMetadataClient(MockSpotify(mocked_artist_response))
        artist_metadata = metadata_client.search_artist(artist=artist)

        self.assertEqual(expected_artist_metadata , artist_metadata)